---
- hosts: webservers

  tasks:
    - name: install chronyd
      ansible.builtin.yum:
        name: chrony
        state: present
    
    - name: start and enable chronyd
      ansible.builtin.service:     
        name: chronyd
        state: started
        enabled: yes

...
