---
# tasks file for httpd
#
- name: install httpd
  ansible.builtin.apt:
    name: apache2
    state: present

- name: start and enable httpd
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: copy index.html to webservers
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
  loop:
    - index.html
    - alpha.html
    - beta.html
    - gama.html

- name: change config and port number
  ansible.builtin.template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify:
    - restart httpd

- name: change config and port number
  ansible.builtin.template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - restart httpd

...
